### ISSUE TITLE
100% code coverage reported for not tested code.

### ISSUE THREAD

**Issue by danielkorzekwa** [mtkopone/scct#16] opened 2011-12-27 23:27 UTC
Not tested method firstServeAvgPct() for the code below.

```
package dk.atp.api

import AtpWorldTourApi._

/**
 * API interface for atpworldtour.com tennis statistics.
 *
 */

object AtpWorldTourApi {

  object PointWonFactEnum extends Enumeration {
    type PointWonFactEnum = Value
    val FIRST_SERVE_POINTS_WON = Value("2")
    val SECOND_SERVE_POINTS_WON = Value("3")
    val FIRST_SERVE_RETURN_POINTS_WON = Value("6")
    val SECOND_SERVE_RETURN_POINTS_WON = Value("7")

    override def toString() = PointWonFactEnum.values.mkString("MatchfactEnum [", ", ", "]")
  }

  object SurfaceEnum extends Enumeration {
    type SurfaceEnum = Value
    val CLAY = Value(1)
    val GRASS = Value(2)
    val HARD = Value(3)

    override def toString() = SurfaceEnum.values.mkString("SurfaceEnum [", ", ", "]")
  }

  /**
   * @param rank
   * @param fullName
   * @param pctWon Percentage of first serve won
   * @param matches Total number of matches
   *
   */
  case class FirstServeFact(rank:Int,fullName: String, pctWon: Double, matches: Int)
  case class FirstServeFacts(playerFacts: List[FirstServeFact]) {
    def firstServeAvgPct() = playerFacts.foldLeft(0d)((sum,fact) => sum + fact.pctWon) / playerFacts.size
  }

  /**
   * @param fullName
   * @param pointsWon Number of points won
   * @param totalPoints Total number of points
   * @param pctWon Percentage of matches won
   * @param matches Total number of matches
   */
  case class PointWonFact(fullName: String, pointsWon: Int, totalPoints: Int, pctWon: Double, matches: Int)
  case class PointWonFacts(playerFacts: List[PointWonFact])

}

import AtpWorldTourApi.PointWonFactEnum._
import AtpWorldTourApi.SurfaceEnum._

trait AtpWorldTourApi {

  /**Match facts statistics http://www.atpworldtour.com/Matchfacts/Matchfacts-Landing.aspx*/
  def firstServeFacts(surface: SurfaceEnum, year: Int): FirstServeFacts

  /**Match facts statistics http://www.atpworldtour.com/Matchfacts/Matchfacts-Landing.aspx*/
  def pointWonFacts(pointWonFact: PointWonFactEnum, surface: SurfaceEnum, year: Int): PointWonFacts

}
```

pom file:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <!-- Project information -->
    <modelVersion>4.0.0</modelVersion>
    <groupId>dk.atp</groupId>
    <artifactId>atpworldtour-api</artifactId>
    <name>atpworldtour-api</name>
    <version>0.1-SNAPSHOT</version>
    <inceptionYear>2011</inceptionYear>
    <url>https://github.com/danielkorzekwa/atpworldtour-api</url>

    <!-- Properties -->
    <properties>
        <scala.version>2.9.1</scala.version>
        <junit.version>4.4</junit.version>
    </properties>

    <!-- Repositories -->
    <repositories>
        <repository>
            <id>scala-tools.org</id>
            <name>Scala-Tools Maven2 Repository</name>
            <url>http://scala-tools.org/repo-releases</url>
        </repository>

    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <id>scala-tools.org</id>
            <name>Scala-Tools Maven2 Repository</name>
            <url>http://scala-tools.org/repo-releases</url>
        </pluginRepository>
    </pluginRepositories>

    <build>
        <sourceDirectory>src/main/scala</sourceDirectory>
        <testSourceDirectory>src/test/scala</testSourceDirectory>

        <resources>
            <resource>
                <filtering>false</filtering>
                <directory>src/main/scala</directory>
                <includes>
                    <include>**/*.scala</include>
                </includes>
            </resource>
            <resource>
                <filtering>false</filtering>
                <directory>src/main/resources</directory>
                <includes>
                    <include>**/*.*</include>
                </includes>
            </resource>
        </resources>
        <testResources>
            <testResource>
                <filtering>false</filtering>
                <directory>src/test/scala</directory>
                <includes>
                    <include>**/*.scala</include>
                </includes>
            </testResource>
            <testResource>
                <filtering>false</filtering>
                <directory>src/test/resources</directory>
                <includes>
                    <include>**/*.*</include>
                </includes>
            </testResource>
        </testResources>

        <plugins>
            <plugin>
                <groupId>org.scala-tools</groupId>
                <artifactId>maven-scala-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                            <goal>testCompile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-eclipse-plugin</artifactId>
                <version>2.8</version>
                <configuration>
                    <downloadSources>true</downloadSources>
                    <buildcommands>
                        <buildcommand>ch.epfl.lamp.sdt.core.scalabuilder</buildcommand>
                    </buildcommands>
                    <additionalProjectnatures>
                        <projectnature>ch.epfl.lamp.sdt.core.scalanature</projectnature>
                    </additionalProjectnatures>
                    <classpathContainers>
                        <classpathContainer>org.eclipse.jdt.launching.JRE_CONTAINER</classpathContainer>
                        <classpathContainer>ch.epfl.lamp.sdt.launching.SCALA_CONTAINER</classpathContainer>
                    </classpathContainers>
                </configuration>
            </plugin>

        </plugins>
    </build>
    <reporting>
        <plugins>
            <plugin>
                <groupId>org.scala-tools</groupId>
                <artifactId>maven-scala-plugin</artifactId>
                <version>2.13.1</version>
            </plugin>
        </plugins>
    </reporting>

    <profiles>
      <profile>
        <id>coverage</id>
        <repositories>
          <repository>
            <id>scct repository</id>
            <url>http://mtkopone.github.com/scct/maven-repo</url>
          </repository>
        </repositories>
        <dependencies>
          <dependency>
            <groupId>reaktor</groupId>
            <artifactId>scct_2.9.1</artifactId>
            <version>0.1-SNAPSHOT</version>
          </dependency>
        </dependencies>
        <build>
          <plugins>
            <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-surefire-plugin</artifactId>
              <version>2.6</version>
              <configuration>
                <systemPropertyVariables>
                  <scct.project.name>${project.name}</scct.project.name>
                  <scct.coverage.file>${project.build.outputDirectory}/coverage.data</scct.coverage.file>
                  <scct.report.dir>${project.build.directory}/coverage-report</scct.report.dir>
                  <scct.source.dir>${project.build.sourceDirectory}</scct.source.dir>
                </systemPropertyVariables>
              </configuration>
            </plugin>
            <plugin>
              <groupId>org.scala-tools</groupId>
              <artifactId>maven-scala-plugin</artifactId>
              <configuration>
                <compilerPlugins>
                  <compilerPlugin>
                    <groupId>reaktor</groupId>
                    <artifactId>scct_2.9.1</artifactId>
                    <version>0.1-SNAPSHOT</version>
                  </compilerPlugin>
                </compilerPlugins>
              </configuration>
            </plugin>        
          </plugins>
        </build>
      </profile>
    </profiles>

    <!-- Dependency management -->
    <dependencies>


        <!-- External dependencies -->
        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-library</artifactId>
            <version>${scala.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jsoup</groupId>
            <artifactId>jsoup</artifactId>
            <version>1.6.1</version>
        </dependency>

        <!-- Test dependencies -->
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

</project>
```

From: https://github.com/danielkorzekwa/atpworldtour-api/blob/master/src/main/scala/dk/atp/api/AtpWorldTourApi.scala

**Comment by mtkopone** [comment] 2012-02-25 17:23
Hello, and sorry for the late late reply.

This is in fact a duplicate of: https://github.com/mtkopone/scct/issues/12

The incorrect numbers stem from both the main and test sources being intrumented, which screws up the instrumentation data.

I updated the instructions for using scct with maven at:
http://mtkopone.github.com/scct/#usage-4-tabs-2

Hope they help.

**Closed as completed by mtkopone** 2012-02-25 17:23 UTC
