### ISSUE TITLE
index.html hasn't been generated in coverage-report dir

### ISSUE THREAD

**Issue by vivanov** [mtkopone/scct#5] opened 2011-01-18 00:21 UTC
I tried to produce report covering tests for Apache ESME project: http://esme.apache.org/. It is built with Scala 2.8.1 and SBT 0.7.4. The problem is that after clean and test-coverage commands have been run (it has taken relativly long time for me btw) file ./target/scala_2.8.0/coverage-report/index.html isn't produced it all (while artifacts in other coverage-\* folders were generated). How do you think, what the reason of this problem is? Do you need some example to see results?

**Comment by mtkopone** [comment] 2011-01-18 12:17
Thanks for the report.

I'll try to duplicate this this week, and see what the problem is.

**Comment by mtkopone** [comment] 2011-01-23 18:21
Hi, 

Turns out the scct sbt-plugin isn't compatible with using scala 2.8.1 with sbt for some reason. 

Before I can fix it, you can test scct by removing the "def.scala.version"-property from project/build.properties. After that, the build will use scala 2.7.7 for starting sbt, but 2.8.1 for compilation and testing, and coverage reports should work.

**Comment by mtkopone** [comment] 2011-01-23 20:02
Hi again, 

This should be fixed now, at least the ESME trunk worked ok with the latest binaries. 

Please have a go again, and let me know if there are any problems.

**Comment by vivanov** [comment] 2011-01-24 00:17
Hi Mikko!

Thank you very much.

You are right, I managed to get report  for ESME generated with sbt builded with scala 2.7.7 (as you pointed I commented out "def.scala.version")

I wasn't able to get report for ESME trunk with 2.8.1 though - "coverage-report" dir is still empty for me.

**Closed as completed** 2011-01-24 04:02 UTC

**Comment by vivanov** [comment] 2011-01-24 16:40
I've just tried to run test-coverage again using SBT+Scala 2.8.1, this time it has been successfully generated! Probably it were some problem on my local machine. Thanks again!!!

**Comment by mtkopone** [comment] 2011-01-25 08:18
Probably the plugin jars just hadn't updated yet.

Good stuff.
