### ISSUE TITLE
initialization code in objects are marked as uncovered.

### ISSUE THREAD

**Issue by mkhettry** [mtkopone/scct#17] opened 2012-03-16 20:29 UTC
In the screen shot, some lines in the initializer for the object and some are not. This can't be possible, right?

http://imgur.com/V7bSH

**Comment by mtkopone** [comment] 2012-03-19 08:20
Shouldn't be possible. Looks like a bug. I'll look into it soon.

Is the source code for your project available?  If so, can you send a link to it for me, so I can try it out?

**Comment by mtkopone** [comment] 2012-03-24 19:49
Hi,

I couldn't reproduce this with any simple test.
By any chance would you have a minimal test case to provide?

Then some speculation:
Are you using maven? If so, it could be that the source files under your test directory are also being instrumented, and then confusing the reporting. This can be fixed by following the updated maven instructions on the home page.

**Comment by mkhettry** [comment] 2012-03-26 23:18
Let me find a small enough test case for you. Thanks for looking into it.

**Comment by mtkopone** [comment] 2012-08-03 07:38
Could not reproduce this. 

Also, the 0.2-SNAPSHOT version of scct includes improved initialization of scct when the test run begins. The startup code might previously have been responsible for this behavior. Since it's now been changed, I'm gonna close this, hoping it _just went away_ :)

Feel free to reopen the issue if it persists.

**Closed as completed by mtkopone** 2012-08-03 07:38 UTC
