### ISSUE TITLE
coverage:compile warnings for ivy 2 dependencies

### ISSUE THREAD

**Issue by jestan** [mtkopone/scct#14] opened 2011-08-31 08:38 UTC
Hi Mikko,

I am using scct with sbt 0.10.1 + https://github.com/dvc94ch/sbt-scct and getting following warnings in  coverage:compile, what could be the cause?

Warning: could not load descriptor for plugin /home/jestan/.ivy2/cache/se.scalablesolutions.akka/akka-actor/jars/akka-actor-1.1.3.jar
Warning: could not load descriptor for plugin /home/jestan/.ivy2/cache/se.scalablesolutions.akka/akka-http/jars/akka-http-1.1.3.jar
Warning: could not load descriptor for plugin /home/jestan/.ivy2/cache/commons-codec/commons-codec/jars/commons-codec-1.4.jar
Warning: could not load descriptor for plugin /home/jestan/.ivy2/cache/javax.ws.rs/jsr311-api/jars/jsr311-api-1.1.jar
Warning: could not load descriptor for plugin /home/jestan/.ivy2/cache/javax.annotation/jsr250-api/jars/jsr250-api-1.0.jar
Warning: could not load descriptor for plugin /home/jestan/.ivy2/cache/se.scalablesolutions.akka/akka-testkit/jars/akka-testkit-1.1.3.jar

scct: Saving coverage data.

**Comment by mtkopone** [comment] 2012-04-23 15:59
Presumably this is caused by something else, as neither scct or the sbt plugin for it have dependencies to any of the jars listed in the output. 

Closing as not reproducible.

**Closed as completed by mtkopone** 2012-04-23 15:59 UTC

**Comment by jestan** [comment] 2012-04-24 06:12
is it because scct compiler plugin jar is added using  -X:plugin < absolute path> in sbt-scct plugin
see https://issues.scala-lang.org/browse/SI-4841

I have to report this issue in sbt-scct plugin :)
